# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-17 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 17, 20, 14, 39, 957072)),
        ),
    ]
