# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-24 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0003_auto_20170424_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user2',
        ),
        migrations.AlterField(
            model_name='test',
            name='testDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 24, 6, 35, 10, 169580)),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
