# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-26 20:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0005_auto_20170426_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 20, 52, 36, 991750)),
        ),
    ]
