# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0007_auto_20170427_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='testDate',
            field=models.DateTimeField(),
        ),
    ]
