# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-27 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0008_auto_20170427_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 18, 12, 43, 80410)),
        ),
    ]
