# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0010_auto_20170427_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to='HealthNet.Doctor'),
        ),
    ]
