# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0011_auto_20170428_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Your Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to='HealthNet.Doctor', verbose_name='Primary Doctor'),
            preserve_default=False,
        ),
    ]
