# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0015_message_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='status',
            new_name='status_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='status_sender',
            field=models.BooleanField(default=True),
        ),
    ]
