# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-05 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_auto_20170505_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='status_receiver',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status_sender',
        ),
    ]
