# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0018_auto_20170507_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
