# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0020_auto_20170507_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
